### ISSUE TITLE
Handle Paragraph 

### ISSUE THREAD

**Issue by eaedk** [jc639/pytorch-handwritingCTC#6]
Morning, 
Please could you gave me some suggestions to modify your model and apply it to a text span image and predict the lines separated by a token.

**Comment by jc639** [comment]
Do you have an example image?

**Comment by eaedk** [comment]
Below is a sample paragraph, and as output something like : 

```python3
output = f"{line001} <end_line> {line002} <end_line>" ...
```

![img](https://www.researchgate.net/profile/Neeta-Nain/publication/299666231/figure/fig1/AS:491693964304386@1494240384780/Example-image-of-a-general-handwritten-text-paragraph-from-IAM-dataset-4.png)

**Comment by jc639** [comment]
You can't handle that image with the model without significant modifications. What you need to do is preprocessing of the image and split the paragraph image into lines images before you pass each line to the model. 

If all your images are like that then you can probably do something quite simple with opencv, process the image to make the text a bit more blocky, and then count dark pixels per pixel row of the image. The gaps between lines are really obvious in that example so will have a high number of white pixels and conversely a low number of dark pixels - choose a line split in the middle of these regions. 

This only would work because the writing is quite neat, not at angle etc. If not all like that then you will likely need something a bit more complex. Have a look on pyimagesearch for any tutorials that might be a good starting point for processing the image - https://www.pyimagesearch.com/topics/
